[package]
name = "try_zip"
version = "0.2.1"
edition = "2021"
description = "Zip with a shorter or optional second iterator."
license = "0BSD"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
